version: "build-{build}"

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\raggaer\castro

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;%PATH%

build_script:
  - ps: .\appveyor_build.ps1

test: off

artifacts:
  - path: buildOutput\tiger_win_amd64.exe
    name: Windows amd64 build
  - path: buildOutput\tiger_linux_amd64
    name: Linux amd64 build
  - path: buildOutput\tiger_linux_arm64
    name: Linux arm64 build
  - path: buildOutput\release.zip
    name: Required data